services:
  okcupid:
    build: .
    volumes:
      - ${SESSION_FILE}:/app/.session
      - ${CONFIG_FILE}:/app/okcupid.json
      - ${LOGS_DIR}:/app/logs
    command: /app/venv/bin/python3 main.py --session ./.session
